lic/lic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lic/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('draft/', views.draft, name='draft'),
    path('<int:post_id>/delete/', views.draft_delete, name='draft_delete'),
    path('<int:post_id>/edit/', views.draft_edit, name='draft_edit'),
    path('<int:post_id>/publish/', views.draft_to_publish, name='draft_to_publish'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
]

lic/news/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.DRAFT)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()
    draft = DraftManager()
    
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title
    
    def like_count(self):
        return self.like_set.count()
    
    def user_liked(self, user):
        return self.like_set.filter(user=user).exists()
    
    def add_like(self, user):
        Like.objects.create(user=user, post=self)

    def remove_like(self, user):
        Like.objects.filter(user=user, post=self).delete()
    

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')

lic/news/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']
    
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'reg_input',
            'placeholder': 'Введите заголовок'
        })
        self.fields['body'].widget.attrs.update({
            'class': 'reg_input',
            'placeholder': 'Напишите текст'
        })
        self.fields['title'].label = 'Заголовок'
        self.fields['body'].label = 'Новость'

lic/news/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.utils.text import slugify
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required


@login_required
def post_list(request):
    post_list = Post.published.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page', 1)
    posts = paginator.page(page_number)

    like_status = {}
    for post in posts:
        like_status[post.id] = post.user_liked(request.user)

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.slug = slugify(post.title)
            if 'published_news' in request.POST:
                post.status = 'PB'
            elif 'draft_news' in request.POST:
                post.status = 'DF'
            post.save()
            form = PostForm()
            return render(request,
                          'news/post/list.html',
                          {'posts': posts, 'form': form, 'like_status': like_status})
    else:
        form = PostForm()

    return render(request,
                  'news/post/list.html',
                  {'posts': posts, 'form': form, 'like_status': like_status})


@login_required
def post_detail(request, id):
    post = get_object_or_404(Post,
                             id=id,
                             status=Post.Status.PUBLISHED)
    like_status = post.user_liked(request.user)

    return render(request,
                  'news/post/detail.html',
                  {'post': post, 'like_status': like_status})


@login_required
def draft(request):
    current_user = request.user
    draft_posts = Post.draft.filter(author=current_user)

    return render(request,
                  'news/post/draft.html',
                  {'draft_posts': draft_posts})


@login_required
def draft_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('news:draft')
    return render(request, 'news/post/draft_post_delete.html', {'post': post})



@login_required
def draft_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('news:draft')
    else:
        form = PostForm(instance=post)
    return render(request, 'news/post/draft_post_edit.html', {'form': form})


@login_required
def draft_to_publish(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.status = 'PB'
        post.save()
        return redirect('news:post_list')
    return render(request, 'news/post/draft_to_publish.html', {'post': post})


@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user_liked(request.user):
        post.remove_like(request.user)
        return redirect('news:post_list')
    post.add_like(request.user)
    return redirect('news:post_list')

lic/news/templates/news/post/detail.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="detail-news">
  {% if post.author.profile.photo %}
    <a href="{% url 'user' post.author.id %}" class="friend-profile-view">
      <img src="{{ post.author.profile.photo.url }}" alt="{{ post.author.username }}" class="details-news-photo">
    </a>
  {% else %}
    <a href="{% url 'user' post.author.id %}" class="friend-profile-view">
      <img src="{% static 'main/img/noPhoto.png' %}" alt="noPhoto" class="details-news-photo">
    </a>
  {% endif %}
  {% if post.author.first_name %}
    <a href="{% url 'user' post.author.id %}" class="friend-profile-view">
      <span class="author-name">{{ post.author.first_name }} {{ post.author.last_name }}</span>
    </a>
  {% else %}
    <a href="{% url 'user' post.author.id %}" class="friend-profile-view">
      {{ post.author }}
    </a>
  {% endif %}
  <br><br>
  <div id="news-title"><h1>{{ post.title }}</h1></div><br>
  <div id="news-body">{{ post.body|linebreaks }}</div><br>
  <div id="published-news"><i>Опубликовано {{ post.publish }}</i></div>
  {% with post_id=post.id %}
    {% if not like_status %}
      <p><a href="{% url 'news:like_post' post.id %}" id="likes">🤍 {{ post.like_count }}</a></p>
    {% else %}
      <p><a href="{% url 'news:like_post' post.id %}" id="likes">❤️ {{ post.like_count }}</a></p>
    {% endif %}
  {% endwith %}
  <button class="guess-num-button" onclick='history.back()'>Вернуться к новостям</button>  
</div>
{% endblock %}

lic/news/templates/news/post/draft.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Черновики{% endblock %}

{% block content %}
<div id="main-news">
  <p id="news-top">Черновики</p>
  <div id="news-blocks">
    {% if not draft_posts %}
    <div class="news">
      <div id="news-body" class="center">Здесь пока ничего нет.</div>
      <button class="guess-num-button" onclick='history.back()'>Назад</button>
    </div>
    {% else %}
      {% for draft_post in draft_posts %}
      <div class="news">
        <div id="news-title"><h3>{{ draft_post.title }}</h3></div>
        <div id="news-body">{{ draft_post.body|truncatewords:30|linebreaks }}
        </div>
        
        <div id="published-news"><i>
        {% if draft_post.updated != draft_post.created %}
          Изменено {{ draft_post.updated }}
        {% else %}
          Создано {{ draft_post.created }}
        {% endif %}        
        </i></div>

        <button class="draft-publish draft-button" onclick="window.location.href = `{% url 'news:draft_to_publish' draft_post.id %}`">Опубликовать</button>
        <button class="change draft-button" onclick="window.location.href = `{% url 'news:draft_edit' draft_post.id %}`">Изменить</button>
        <button class="delete draft-button" onclick="window.location.href = `{% url 'news:draft_delete' draft_post.id %}`">Удалить</button>
      </div><br>
      {% endfor %}
        <button class="guess-num-button" onclick="window.location.href = `{% url 'news:post_list' %}`">Назад</button>
      {% endif %}
    </div>
  </div>
{% endblock %}

lic/news/templates/news/post/draft_post_delete.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Удаление{% endblock %}

{% block content %}
<div class="detail-news">
  <p id="draft-delete-title">Удаление:</p><br><br>
  <p class="draft-delete-body">Вы уверены, что хотите удалить новость "{{ post.title }}"?</p><br><br>
  <form method="post" id="draft-delete-form">
      {% csrf_token %}
      <button type="submit" class="delete draft-button">Да, удалить</button>
      <button type="button" onclick="history.back()" class="draft-publish draft-button">Отмена</button>
    </form>
</div>
{% endblock %}

lic/news/templates/news/post/draft_post_edit.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Редактировать новость{% endblock %}

{% block content %}
<div id="main-news">
  <p id="news-top">Редактировать новость:</p><br><br>
  <form method="post" class="add_news">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="draft-publish draft-button">Сохранить изменения</button>
      <button type="button" onclick="history.back()" class="delete draft-button">Отмена</button>
    </form>
</div>
{% endblock %}

lic/news/templates/news/post/draft_to_publish.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Публикация{% endblock %}

{% block content %}
<div class="detail-news">
  <p id="draft-delete-title">Публикация:</p><br><br>
  <p class="draft-delete-body">Вы уверены, что хотите опубликовать новость "{{ post.title }}"?</p><br><br>
  <form method="post" id="draft-delete-form">
      {% csrf_token %}
      <button type="submit" class="draft-publish draft-button">Опубликовать</button>
      <button type="button" onclick="history.back()" class="delete draft-button">Отмена</button>
    </form>
</div>
{% endblock %}

lic/news/templates/news/post/list.html
{% extends 'main/layout.html' %}
{% load static %}
{% load dict_filter %}

{% block title %}Новости{% endblock %}

{% block content %}
<div id="main-news">
  <p id="news-top">Новости</p>
  <form method="post" class="add_news">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="published_news">Опубликовать новость</button>
    <button type="submit" name="draft_news">Сохранить в черновики</button>
    <button onclick="window.location.href = `{% url 'news:draft' %}`">Просмотреть черновики</button>
  </form>
  <div id="news-blocks">
    {% for post in posts %}
    <div class="news">
      {% if post.author.profile.photo %}
        <a href="{% url 'user' post.author.id %}" class="friend-profile-view">
          <img src="{{ post.author.profile.photo.url }}" alt="{{ post.author.username }}" class="profile-photo"> 
        </a>
      {% else %}
        <a href="{% url 'user' post.author.id %}" class="friend-profile-view">
          <img src="{% static 'main/img/noPhoto.png' %}" alt="noPhoto" class="profile-photo">
        </a>
      {% endif %}
      {% if post.author.first_name %}
        <a href="{% url 'user' post.author.id %}" class="friend-profile-view"> {{ post.author.first_name }} {{ post.author.last_name }}</a>
      {% else %}
        <a href="{% url 'user' post.author.id %}" class="friend-profile-view">{{ post.author }}</a>
      {% endif %}
      <div id="news-title"><h3>{{ post.title }}</h3></div>
      <div id="news-body">{{ post.body|truncatewords:30|linebreaks }}
      <a href="{% url 'news:post_detail' post.id %}"> Читать полностью </a>
      </div><br>
      {% with post_id=post.id %}
        {% if not like_status|dict:post_id %}
          <p><a href="{% url 'news:like_post' post.id %}" id="likes">🤍 {{ post.like_count }}</a></p>
        {% else %}
          <p><a href="{% url 'news:like_post' post.id %}" id="likes">❤️ {{ post.like_count }}</a></p>
        {% endif %}
      {% endwith %}
      <div id="published-news"><i>Опубликовано {{ post.publish }}</i></div>
    </div><br>
    {% endfor %}
  </div>
  {% include "pagination.html" with page=posts %}
</div>
{% endblock %}