lic/friends/urls.py
from django.urls import path
from . import views

app_name = 'friends'

urlpatterns = [
    path('', views.friends_list, name='friends_list'),
    path('search', views.search_users, name='search_users'),
    path('add_friend', views.add_friend, name='add_friend'),
    path('followers', views.followers, name='followers'),
] 

lic/lic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lic/main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
    path('settings/', views.settings, name='settings'),
    path('user/<int:user_id>', views.user, name='user'),
    path('friends/', include('friends.urls', namespace='friends')),
    path('news/', include('news.urls', namespace='news')),
    path('games/', include('games.urls')),
    path('message/', include('message.urls')),
]

lic/message/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.message_list, name='message_list'),
]

lic/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('draft/', views.draft, name='draft'),
    path('<int:post_id>/delete/', views.draft_delete, name='draft_delete'),
    path('<int:post_id>/edit/', views.draft_edit, name='draft_edit'),
    path('<int:post_id>/publish/', views.draft_to_publish, name='draft_to_publish'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
]

lic/message/models.py
from django.db import models

# Create your models here.

lic/main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render


@login_required
def main(request):
    return render(request, 'main/mainPage.html')

@login_required
def about(request):
    return render(request, 'main/about.html')

@login_required
def settings(request):
    return render(request, 'main/settings.html')

@login_required
def user(request, user_id):
    viewed_user = User.objects.get(id=user_id)
    return render(request, 'main/user.html',
                  {'viewed_user': viewed_user})

lic/message/views.py
from django.shortcuts import render

def message_list(request):
    return render(request, 'message/message_list.html')

lic/main/templates/main/about.html
{% extends 'main/layout.html' %}


{% block title %}О нас{% endblock %}
{% block content %}
<div id="content">
    <div id="about">
        <h1>Юсуф Богатырев - студент TOP-Academy.</h1></div>
    </div>
{% endblock %}

lic/main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
  <link rel="icon" href="{% static 'main/images/favicon.ico' %}">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>    
  <header>
    <div id="header-logo">
      <a {% block logo_touch %}href="{% url 'main' %}"{% endblock %}><img src="{% static 'main/img/LIClogo.png' %}" id="icon" ></a>
    </div>
    <div id="header-entry">
      {% block foto %}
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" id="header-entry-button">Выйти</button>
      </form>
      {% if user.profile.photo %}
      <img src="{{ user.profile.photo.url }}" alt="photo" id="round">
      {% else %}
      <img src="{% static 'main/img/noPhoto.png' %}" alt="photo" id="round">
      {% endif %}
      {% endblock %}
    </div>
  </header>
  <main>
    {% block navigation %}
    <div id="left-nav">
      <aside>
        <ul id="nav_ul">
          <li class="nav_li"><a href="{% url 'main' %}" class="a-nav">Главная</a></li>
          <li class="nav_li"><a href="{% url 'news:post_list' %}" class="a-nav">Новости</a></li>
          <li class="nav_li"><a href="{% url 'friends:friends_list' %}" class="a-nav">Друзья</a></li>
          <li class="nav_li"><a href="{% url 'message_list' %}" class="a-nav">Сообщения</a></li>
          <li class="nav_li"><a href="{% url 'games' %}" class="a-nav">Игры</a></li>
          <li class="nav_li"><a href="{% url 'settings' %}" class="a-nav">Настройки</a></li>
          <li class="nav_li"><a href="{% url 'about' %}" class="a-nav">О нас</a></li>
        </ul>
      </aside>
    </div>
    {% endblock %}
    {% block content %}{% endblock %}
  </main>
  <footer>
    <h4>Юсуф Богатырев 2024 &copy;</h4>
  </footer>
</body>
</html>

lic/main/templates/main/mainPage.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Главная страница{% endblock %}
{% block content %}
<div id="mainPageContainer">
  <div id="profile-header">
    <div>
      {% if user.profile.photo %}
      <img src="{{ user.profile.photo.url }}" alt="photo" id="main-photo">
      {% else %}
      <img src="{% static 'main/img/noPhoto.png' %}" id="main-photo">
      {% endif %}
    </div>
    <div class="header-name">
      <p id="user-inform">
        {% if user.first_name %}
          {{ user.first_name }} {{ user.last_name }}
        {% else %}
          {{ user }}
        {% endif %}
      </p>
      {% if user.profile.country and user.profile.city %}
        <p id="location">📍 {{ user.profile.country }}, {{ user.profile.city }} </p>
      {% endif %}
    </div>
      <div class="header-func">
        <button onclick="window.location.href = `{% url 'edit' %}`">Редактировать профиль</button>
      </div>
  </div>
  <div id="profile-body">
    <br><br>
    <p>Контент не подвезли...</p>
  </div>
</div>
{% endblock %}

lic/main/templates/main/message.html
{% extends 'main/layout.html' %}


{% block title %}Сообщения{% endblock %}
{% block content %}
<div id="content"><center><h1>Это сообщения!!</h1></center></div>
{% endblock %}

lic/main/templates/main/settings.html
{% extends 'main/layout.html' %}


{% block title %}Настройки{% endblock %}
{% block content %}
<div id="content">
  <ul id="settings">
    <li><a href="{% url 'edit' %}">Редактировать аккаунт</a></li>
    <li><a href="{% url 'password_change' %}">Изменить пароль</a></li>
  </ul>
  
</div>
{% endblock %}

lic/main/templates/main/user.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Главная страница{% endblock %}
{% block content %}
<div id="mainPageContainer">
  <div id="profile-header">
    <div>
      {% if viewed_user.profile.photo %}
      <img src="{{ viewed_user.profile.photo.url }}" alt="photo" id="main-photo">
      {% else %}
      <img src="{% static 'main/img/noPhoto.png' %}" id="main-photo">
      {% endif %}
    </div>
    <div class="header-name">
      <p id="viewed_user-inform">
        {% if viewed_user.first_name %}
          {{ viewed_user.first_name }} {{ viewed_user.last_name }}
        {% else %}
          {{ viewed_user }}
        {% endif %}
      </p>
      {% if viewed_user.profile.country and viewed_user.profile.city %}
        <p id="location">📍 {{ viewed_user.profile.country }}, {{ viewed_user.profile.city }} </p>
      {% endif %}
    </div>
  </div>
  <div id="profile-body">
    <br><br>
    <p>Контент не подвезли...</p>
  </div>
</div>
{% endblock %}