lic/friends/urls.py
from django.urls import path
from . import views

app_name = 'friends'

urlpatterns = [
    path('', views.friends_list, name='friends_list'),
    path('search', views.search_users, name='search_users'),
    path('add_friend', views.add_friend, name='add_friend'),
    path('followers', views.followers, name='followers'),
] 

lic/lic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lic/friends/forms.py
from django import forms

class UserSearch(forms.Form):
    search = forms.CharField(label='Поиск друзей',
                               widget=forms.TextInput)
    def __init__(self, *args, **kwargs):
        super(UserSearch, self).__init__(*args, **kwargs)
        self.fields['search'].widget.attrs.update({
            'class': 'reg_input',
            'placeholder': 'Введите запрос'})

lic/friends/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render
from friendship.models import Friend, Follow, FriendshipRequest
from .forms import UserSearch


@login_required
def friends_list(request):
    friends = Friend.objects.friends(request.user)
    friends_count = len(friends)
    num_unrejected_requests = Friend.objects.unrejected_request_count(request.user)
    if request.method == 'POST':
        if request.POST.get('write_message'):
            ...
        elif request.POST.get('delete_friend'):
            user_id = request.POST.get('to_user_id')
            to_user = User.objects.get(id=user_id)
            from_user = request.user
            Friend.objects.remove_friend(from_user, to_user)
            Follow.objects.add_follower(to_user, from_user)
            return followers(request)

    return render(request,
                  'friends/friendsMain.html',
                  {'friends': friends,
                   'friends_count':friends_count,
                   'num_unrejected_requests':num_unrejected_requests})

@login_required
def search_users(request):
    form = UserSearch()
    user_list = False
    already_requested = {}
    background_color = {}

    if request.method == 'POST':
        if request.POST.get('search'):
            query_name = request.POST.get('search')
            user_list = User.objects.all()
            for term in query_name.split():
                user_list = user_list.filter(Q(first_name__icontains=term) | Q(last_name__icontains=term))
            for user in user_list:
                if FriendshipRequest.objects.filter(
                    from_user=request.user, to_user=user).exists():
                    already_requested[user.id] = 'Запрос отправлен'
                    background_color[user.id] = 'rgb(52, 205, 52)'
                elif FriendshipRequest.objects.filter(
                    from_user=user, to_user=request.user).exists():
                    already_requested[user.id] = 'Принять запрос'
                    background_color[user.id] = 'yellowgreen'
                elif Friend.objects.are_friends(user, request.user):
                    already_requested[user.id] = 'Удалить из друзей'
                    background_color[user.id] = 'red'
                else:
                    already_requested[user.id] = 'Добавить в друзья'
                    background_color[user.id] = 'grey'
            
        elif not request.POST.get('search') and request.POST.get('to_user'):
            user_id = request.POST.get('to_user')
            to_user = User.objects.get(id=user_id)
            from_user = request.user
            if request.POST.get('status_fr_request') == 'Добавить в друзья': 
                Friend.objects.add_friend(from_user, to_user)
            elif request.POST.get('status_fr_request') == 'Запрос отправлен':
                friend_request = FriendshipRequest.objects.get(from_user=from_user, to_user=to_user)
                friend_request.cancel()
            elif request.POST.get('status_fr_request') == 'Принять запрос':
                friend_request = FriendshipRequest.objects.get(from_user=to_user, to_user=from_user)
                friend_request.accept()
            elif request.POST.get('status_fr_request') == 'Удалить из друзей':
                Friend.objects.remove_friend(from_user, to_user)
                Follow.objects.add_follower(to_user, from_user)
                return followers(request)

    return render(request,
                  'friends/search_users.html', 
                  {'form':form,
                   'user_list':user_list,
                   'already_requested':already_requested,
                   'background_color':background_color
                   })


@login_required
def add_friend(request):
    num_unrejected_requests = Friend.objects.unrejected_request_count(request.user)
    friendship_requests = Friend.objects.requests(user=request.user)
    if request.POST:
        user_id = request.POST.get('user_id')
        to_user = User.objects.get(id=user_id)
        from_user = request.user
        if request.POST.get('add_friend'):
            friend_request = FriendshipRequest.objects.get(from_user=to_user, to_user=from_user)
            friend_request.accept()
            return friends_list(request)
        elif request.POST.get('follower'):
            friend_request = FriendshipRequest.objects.get(from_user=to_user, to_user=from_user)
            friend_request.cancel()
            Follow.objects.add_follower(to_user, from_user)
            return followers(request)
    return render(request,
                  'friends/friends_request_add.html',
                  {'friendship_requests': friendship_requests,
                   'num_unrejected_requests':num_unrejected_requests})

@login_required
def followers(request):
    num_unrejected_requests = Friend.objects.unrejected_request_count(request.user)
    followers = Follow.objects.followers(request.user)
    fol_count = len(followers)
    return render(request,
                  'friends/followers.html',
                  {'followers': followers,
                   'fol_count':fol_count,
                   'num_unrejected_requests':num_unrejected_requests})

lic/friends/templates/friends/followers.html
{% extends 'main/layout.html' %}
{% load static %}


{% block title %}Подписчики{% endblock %}
{% block content %}
<div id="friendsContainer">
  <div id="infoPanel">
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:friends_list' %}`">Мои друзья</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:followers' %}`">Подписчики</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:add_friend' %}`">Запросы в друзья {{ num_unrejected_requests }}</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:search_users' %}`">Найти друзей</button>
  </div>
    <h2>Мои подписчики {{ fol_count }}</h2>
    {% for follower in followers %}
        <div class="container-for-friends-list">
          <div class="fr-requests-container">
            {% if follower.profile.photo %}
            <a href="{% url 'user' follower.id %}">
              <img src="{{ follower.profile.photo.url }}"
                alt="{{ follower.first_name }}" 
                class="fr-request-photo">
            </a>
            {% else %}
              <a href="{% url 'user' follower.id %}">
                <img src="{% static 'main/img/noPhoto.png' %}" alt="noPhoto" class="fr-request-photo">
              </a>
            {% endif %}
          </div>
          <div class="fr-requests-container"> 
            <a href="{% url 'user' follower.id %}" class="friend-profile-view">{{ follower.first_name }} {{ follower.last_name }}</a> <br>
            {% if follower.profile.country and follower.profile.city %}
              <p id="location-follower">📍 {{ follower.profile.country }}, {{ follower.profile.city }} </p>
            {% endif %} <br>
            <div>
              <button class="fr-message-btn">Написать сообщение</button>
            </div>
          </div>
        </div>
    {% empty %}
        <h3>У вас нет подписчиков.</h3>
    {% endfor %}
</div>
{% endblock %}

lic/friends/templates/friends/friendsMain.html
{% extends 'main/layout.html' %}
{% load static %}


{% block title %}Друзья{% endblock %}
{% block content %}
<div id="friendsContainer">
  <div id="infoPanel">
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:friends_list' %}`">Мои друзья</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:followers' %}`">Подписчики</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:add_friend' %}`">Запросы в друзья {{ num_unrejected_requests }}</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:search_users' %}`">Найти друзей</button>
  </div>
    <h2>Мои друзья {{ friends_count }}</h2>
    {% for friend in friends %}
        <div class="container-for-friends-list">
          <div class="fr-requests-container">
            {% if friend.profile.photo %}
              <a href="{% url 'user' friend.id %}">
                <img src="{{ friend.profile.photo.url }}"
                  alt="{{ friend.first_name }}" 
                  class="fr-request-photo">
              </a>
            {% else %}
              <a href="{% url 'user' friend.id %}">
                <img src="{% static 'main/img/noPhoto.png' %}" alt="noPhoto" class="fr-request-photo">
              </a>
            {% endif %}
          </div>
          <div class="fr-requests-container"> 
            <a href="{% url 'user' friend.id %}" class="friend-profile-view">{{ friend.first_name }} {{ friend.last_name }}</a> <br>
            {% if friend.profile.country and friend.profile.city %}
              <p id="location-friend">📍 {{ friend.profile.country }}, {{ friend.profile.city }} </p>
            {% endif %} <br>
            <div>
              <form method="post" id="form-btn-friend">
                {% csrf_token %}
                <input type="hidden" name="to_user_id" value="{{ friend.id }}"/>
                <input type="submit" name="write_message" value="Написать сообщение" class="fr-message-btn"/>
                <input type="submit" name="delete_friend" value="Удалить из друзей" class="fr-delete-btn"/>
              </form>

            </div>
          </div>
        </div>
    {% empty %}
        <h3>У вас нет друзей.</h3>
    {% endfor %}
</div>
{% endblock %}

lic/friends/templates/friends/friends_request_add.html
{% extends 'main/layout.html' %}
{% load static %}


{% block title %}Запросы в друзья{% endblock %}
{% block content %}
<div id="friendsContainer">
  <div id="infoPanel">
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:friends_list' %}`">Мои друзья</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:followers' %}`">Подписчики</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:add_friend' %}`">Запросы в друзья {{ num_unrejected_requests }}</button>
    <button id="friendSearch" onclick="window.location.href = `{% url 'friends:search_users' %}`">Найти друзей</button>
  </div>
    <h2>Запросы в друзья</h2>
      {% for f_r in friendship_requests %}
          <div class="container-for-friends-list">
            <div class="fr-requests-container">
              {% if f_r.from_user.profile.photo %}
                <a href="{% url 'user' f_r.from_user.id %}">
                  <img src="{{ f_r.from_user.profile.photo.url }}"
                    alt="{{ f_r.from_user.profile.photo.user.first_name }}" 
                    class="fr-request-photo">
                </a>
                {% else %}
                <a href="{% url 'user' f_r.from_user.id %}">
                  <img src="{% static 'main/img/noPhoto.png' %}" alt="noPhoto" class="fr-request-photo">
                </a>
            {% endif %}
            </div>
            <div class="fr-requests-container">
              <a href="{% url 'user' f_r.from_user.id %}" class="friend-profile-view" >
                {{ f_r.from_user.first_name }}
                {{ f_r.from_user.last_name }}
              </a>
              <div class="friendship_requests">
                {{ f_r.message }}
              </div>
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{ f_r.from_user.id }}"/>
                <input type="submit" name="add_friend" value="Добавить в друзья" class="fr-request-btn"/>
                <input type="submit" name="follower" value="Оставить в подписчиках" class="fr-request-btn"/>
              </form>
            </div>
          </div>
        {% empty %}
        <h3>У вас нет запросов на добавление</h3>
      {% endfor %}
</div>
{% endblock %}

lic/friends/templates/friends/search_users.html
{% extends 'main/layout.html' %}
{% load static %}
{% load friendshiptags %}
{% load dict_filter %}


{% block title %}Поиск друзей{% endblock %}
{% block content %}
<div id="content">
  <form method="post" class="searchUsers">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Поиск</button>
  </form>
  {% if user_list %}
    <div id="search-users-list-blocks">
      {% for q_user in user_list %}
        {% if user.id != q_user.id %}
          <div class="search-users-list">
            {% if q_user.profile.photo %}
              <a href="{% url 'user' q_user.id %}">
                <img src="{{ q_user.profile.photo.url }}" alt="{{ q_user.username }}" class="profile-photo">
              </a>
            {% else %}
              <a href="{% url 'user' q_user.id %}">
                <img src="{% static 'main/img/noPhoto.png' %}" alt="noPhoto" class="profile-photo">
              </a>
            {% endif %}
            {% if q_user.first_name %}
              <a href="{% url 'user' q_user.id %}" class="friend-profile-view" >
                {{ q_user.first_name }} {{ q_user.last_name }}
              </a>
            {% else %}
              <a href="{% url 'user' q_user.id %}" class="friend-profile-view" >{{ q_user }} </a>
            {% endif %}
            {% if q_user.profile.country and q_user.profile.city %}
              <p id="search-users-location">📍 {{ q_user.profile.country }}, {{ q_user.profile.city }} </p>
            {% endif %}
            
            {% if not q_user.id == request.user.id %}
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="to_user" value="{{ q_user.id }}" />
                <input type="submit" name="status_fr_request" value="{{ already_requested|dict:q_user.id }}" 
                 style="background-color: {{ background_color|dict:q_user.id }}"/>
              </form>
            {% endif %}
            <div style="background-color: rgb(52, 205, 52);" ></div>
          </div><br>
        {% endif %}
      {% endfor %}
    </div>
  {% endif %}
</div>
{% endblock %}